# Guacamole Data Diode - Secure remote access using the Guacamole remote access using data-diodes.
# Copyright (C) 2020-2026  Maurice Snoeren
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

services:
  postgres:
    image: postgres:15
    container_name: guac_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: guacamole
      POSTGRES_PASSWORD: some-password
      POSTGRES_DB: guacamole_db
    volumes:
      - "initdb:/docker-entrypoint-initdb.d:ro"
      - db-data:/var/lib/postgresql/data
    networks:
      - guac_internal

  guacamole:
    image: guacamole/guacamole:1.5.5
    container_name: guacamole
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole
      POSTGRES_PASSWORD: some-password

      # Point Guacamole at the bridge container
      GUACD_HOSTNAME: host.docker.internal
      GUACD_PORT: 4822
    volumes:
      - "initdb:/opt/guacamole/extensions/guacamole-auth-jdbc/postgresql/schema:ro"
    ports:
      - "8080:8080"  # Guacamole web UI
    networks:
      - guac_internal
    # Make sure Guacamole can talk to the bridge that is on the host network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Converts between TCP and UDP when sending and receiving over the bridge
  guac-bridge:
    build:
      context: ./
    container_name: guac_bridge
    restart: unless-stopped
    stop_grace_period: 1s
    # Runs on the host machine's network
    network_mode: "host"
    command:
      [
        "python", "/app/lbridgeadapter.py",
        "--listen-ip", "0.0.0.0",

        # Where guacd lives
        "--listen-port", "4822",
        "--udp-in-ip", "0.0.0.0",
        "--udp-in-port", "5601",       # Port where UDP is received
        "--udp-out-ip", "10.0.0.2",   # IP where UDP is sent to
        "--udp-out-port", "5501",
      ]

volumes:
  db-data:
  initdb:

networks:
  guac_internal:
