services:
  lrx_proxy:
    build:
      context: ../../
      dockerfile: docker/include/lrx_proxy/Dockerfile
    stop_grace_period: 1s
    container_name: lrx_proxy
    restart: unless-stopped
    network_mode: "host"
    command:
      [
        "./build/lrx_proxy",
        "5503",
        "10.0.4.2", "5504"
      ]
