services:
  guacd:
    image: guacamole/guacd:1.5.5
    container_name: guacd
    restart: unless-stopped
    networks:
      - guacd_internal
    # guacd listens on 4822 TCP by default
    ports:
      - "4822:4822"

  guac-bridge:
    build:
      context: ./
    container_name: guacd_bridge
    restart: unless-stopped
    # Kill container after x time, instead of waiting 10s before shutdown
    stop_grace_period: 1s
    depends_on:
      - guacd
    network_mode: "host"
    # As above, host networking simplifies using the diode NICs and ARP
    command:
      [
        "python", "/app/hbridgeadapter.py",
        "--guacd-ip", "127.0.0.1",
        "--guacd-port", "4822",
        "--udp-in-ip", "0.0.0.0", # Receives UDP traffic
        "--udp-in-port", "5501",
        "--udp-out-ip", "10.0.1.2", # Sends UDP traffic
        "--udp-out-port", "5601",
      ]

networks:
  guacd_internal:
