# Guacamole Data Diode - Secure remote access using the Guacamole remote access using data-diodes.
# Copyright (C) 2020-2026  Maurice Snoeren
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

services:
  guacd:
    image: guacamole/guacd:1.5.5
    container_name: guacd
    restart: unless-stopped
    networks:
      - guacd_internal
    # guacd listens on 4822 TCP by default
    ports:
      - "4822:4822"

  guac-bridge:
    build:
      context: ./
    container_name: guacd_bridge
    restart: unless-stopped
    # Kill container after x time, instead of waiting 10s before shutdown
    stop_grace_period: 1s
    depends_on:
      - guacd
    network_mode: "host"
    # As above, host networking simplifies using the diode NICs and ARP
    command:
      [
        "python", "/app/hbridgeadapter.py",
        "--guacd-ip", "127.0.0.1",
        "--guacd-port", "4822",
        "--udp-in-ip", "0.0.0.0", # Receives UDP traffic
        "--udp-in-port", "5501",
        "--udp-out-ip", "10.0.1.2", # Sends UDP traffic
        "--udp-out-port", "5601",
      ]

networks:
  guacd_internal:
