name: 3dd-5node-guardnode

include:
  - ../include/guard/compose.yml

services:
  guard:
    command:
      [
        "./build/guard",
        "5500",
        "10.0.1.2", "5501"
      ]
    ports:
      - "5500:5500/udp"
      - "4999:4999/udp" # Approval-toggle control port 
