name: 3dd-5node-hightxnode

include:
  - ../include/gcdbroker/compose.yml
  - ../include/guacd/compose.yml

services:
  gcdbroker:
    command:
      [
        "./build/gcdbroker",
        "guacd", "4822",
        "5502",
        "10.0.3.2", "5503"
      ]
    ports:
      - "5502:5502/udp"
