name: 3dd-1node

include:
  - ../include/gmwebserver/compose.yml
  - ../include/gmlbroker/compose.yml
  - ../include/guard/compose.yml
  - ../include/hrx_proxy/compose.yml
  - ../include/gcdbroker/compose.yml
  - ../include/guacd/compose.yml
  - ../include/lrx_proxy/compose.yml

services:
  gmlbroker:
    command:
      [
        "./build/gmlbroker",
        "127.0.0.1", "4823",
        "127.0.0.1", "5504",
        "127.0.0.1", "5500"
      ]

  guard:
    command:
      [
        "./build/guard",
        "5500",
        "127.0.0.1", "5501"
      ]

  hrx_proxy:
    command:
      [
        "./build/hrx_proxy",
        "5501",
        "127.0.0.1", "5502"
      ]

  gcdbroker:
    command:
      [
        "./build/gcdbroker",
        "127.0.0.1", "4822",
        "127.0.0.1", "5502",
        "127.0.0.1", "5503"
      ]

  lrx_proxy:
    command:
      [
        "./build/lrx_proxy",
        "5503",
        "127.0.0.1", "5504"
      ]

volumes:
  db-data:

networks:
  guac_internal:
  guacd_internal:
