name: 3dd-3node-highnode

include:
  - ../include/gcdbroker/compose.yml
  - ../include/guacd/compose.yml

services:
  gcdbroker:
    command:
      [
        "./build/gcdbroker",
        "guacd", "4822",
        "5501",
        "10.0.2.2", "5502"
      ]
    ports:
      - "5501:5501"
