name: 3dd-3node-lownode

include:
  - ../include/gmwebserver/compose.yml
  - ../include/gmlbroker/compose.yml
  - ../include/sshd/compose.yml
  - ../include/nettest/compose.yml

services:
  gmlbroker:
    command:
      [
        "./build/gmlbroker",
        "gmlbroker", "4823",
        "5502",
        "10.0.0.2", "5500"
      ]
    ports:
      - "5502:5502/udp"

  nettest:
    volumes:
      - ./nettest-reports:/var/log/nettest
