services:
  gcdbroker:
    build:
      context: ../../../
      dockerfile: docker/include/gcdbroker/Dockerfile
    environment:
      QUEUE_STATS_MS: 1000
    stop_grace_period: 5s
    container_name: gcdbroker
    restart: unless-stopped
