services:
  gmlbroker:
    build:
      context: ../../
      dockerfile: docker/ltx_proxy/Dockerfile
    stop_grace_period: 1s
    container_name: gmlbroker
    restart: unless-stopped
    network_mode: "host"
    command:
      [
        "./build/gmlbroker",
        "0.0.0.0", "4822",
        "0.0.0.0", "5501",
        "10.0.0.2", "5502"
      ]
