name: 3dd-single-machine
include:
  - ../gmlbroker/compose.yml
  - ../gcdbroker/compose.yml
  - ../guard/compose.yml
  - ../hrx_proxy/compose.yml
  - ../lrx_proxy/compose.yml
  - ../htx_proxy/compose.yml
  - ../ltx_proxy/compose.yml
services: {}
