# Guacamole Data Diode - Secure remote access using the Guacamole remote access using data-diodes.
# Copyright (C) 2020-2026  Maurice Snoeren
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

services:
  guacamole_db:
    image: postgres:15
    container_name: guacamole_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_pass
    volumes:
      - db-data:/var/lib/postgresql/data
      - "initdb:/docker-entrypoint-initdb.d:ro"

  guacamole:
    image: guacamole/guacamole:1.6.0
    container_name: guacamole
    restart: unless-stopped
    depends_on:
      - guacamole_db
    environment:
      # DB config
      POSTGRESQL_HOSTNAME: guacamole_db
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: guacamole_user
      POSTGRESQL_PASSWORD: guacamole_pass

      GUACD_HOSTNAME: gmlbroker
      GUACD_PORT: 4823

      BAN_MAX_INVALID_ATTEMPTS: 9999
    ports:
      - "8080:8080"  # Guacamole web UI
    volumes:
      - "initdb:/opt/guacamole/extensions/guacamole-auth-jdbc/postgresql/schema:ro"

volumes:
  db-data:
  initdb:
