services:
  hrx_proxy:
    build:
      context: ../../../
      dockerfile: docker/include/hrx_proxy/Dockerfile
    stop_grace_period: 1s
    container_name: hrx_proxy
    restart: unless-stopped
    network_mode: "host"
    command:
      [
        "./build/hrx_proxy",
        "5501",
        "10.0.2.2", "5502"
      ]
