name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
       
    steps:
    
    - uses: actions/checkout@v4
    - name: build gmdatadiode
      run: |
       cd gmdatadiode
       make
       
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DH_USERNAME }}
        password: ${{ secrets.DH_PASSWORD }}
        
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
       
#    - name: build docker
#      run: |
#       cd docker/gmserver
#       ./build.sh
       
