name: build

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
       
    steps:
    
    - uses: actions/checkout@v4
    - name: build gmdatadiode
      run: |
       cd gmdatadiode
       make
       
