name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DH_USERNAME }}
        password: ${{ secrets.DH_PASSWORD }}
        
    - name: build gmdatadiode
      run: |
       echo ${{ secrets.dh_username }}
       cd gmdatadiode
       make
       ls -l ../build
    - name: build docker
      run: |
       cd docker/gmserver
       ./build.sh
       
