name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build gmdatadiode
      run: |
       echo ${{ secrets.dh_username }}
       cd gmdatadiode
       make
       ls -l ../build
    - name: build docker
      run: |
       cd ../docker/gmserver
       ./build.sh
       
