name: docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
       
    steps:
    
    - uses: actions/checkout@v4
    - name: build gmdatadiode
      run: |
       cd gmdatadiode
       make
       cd ..
       cp -v build/gmserver docker/gmserver/.
       cp -v build/gmclient docker/gmclient/.
       cp -v build/gmproxyin docker/gmproxyin/.
       cp -v build/gmproxyout docker/gmproxyout/.
       
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DH_USERNAME }}
        password: ${{ secrets.DH_PASSWORD }}
        
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:docker/gmserver"
        push: true
        tags: macsnoeren/gmdatadiode-gmserver:latest

    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:docker/gmclient"
        push: true
        tags: macsnoeren/gmdatadiode-gmclient:latest

    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:docker/gmproxyin"
        push: true
        tags: macsnoeren/gmdatadiode-gmproxyin:latest

    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:docker/gmproxyout"
        push: true
        tags: macsnoeren/gmdatadiode-gmproxyout:latest    
